package com.payoman.nammabooth.models

data class Voter(
    val partNo: String,
    val latitude: String?,
    val longitude: String?,
    val acno: String?,
    val sectionNo: String?,
    val sno: String?,
    val houseNoEn: String?,
    val houseNo: String?,
    val voterNameEn: String?,
    val voterNameKan: String?,
    val sex: String?,
    val relationNameEn: String?,
    val relationNameKan: String?,
    val relationType: String?,
    val age: String?,
    val voterId: String?,
    val statusType: String?,
    val poolingStation: String?,
    val sectionNameEn: String?,
    val sectionNameKan: String?,
    val districtNo: String?,
    val pincode: String?,
    val houseHeadMobileNo: String?,
    val houseHeadNameAndMembers: String?,
    val houseHeadRelationship: String?,
    val houseHeadGender: String?,
    val religion: String?,
    val caste: String?,
    val motherTongue: String?,
    val electionCommissionIdentityCardNo: String?,
    val mobileNo: String?
)
